{{ if .Values.docker_registry.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-docker-registry-auth
    namespace: infrabox-system
    labels:
        app: infrabox
        infrabox.net/component: docker-registry-auth
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: infrabox
                infrabox.net/component: docker-registry-auth
        spec:
            {{- if .Values.docker_registry.node_selector }}
            nodeSelector:
{{ toYaml .Values.docker_registry.node_selector | indent 16 }}
            {{- end }}
            containers:
            {{ include "containers_database" . | indent 12 }}
            -
                name: auth
                image: {{ .Values.general.docker_registry }}/{{ default "infrabox/docker-registry/auth" .Values.docker_registry.auth_image }}:{{ .Values.docker_registry.auth_tag }}
                imagePullPolicy: Always
                env:
                {{ include "env_database" . | indent 16 }}
                {{ include "env_docker_registry" . | indent 16 }}
                livenessProbe:
                    httpGet:
                        path: /ping
                        port: 8080
                    initialDelaySeconds: 5
                    periodSeconds: 30
                readinessProbe:
                    httpGet:
                        path: /ping
                        port: 8080
                    initialDelaySeconds: 3
                    periodSeconds: 3
            volumes:
                {{ include "volumes_database" . | indent 16 }}
{{ end }}
