{{ if .Values.docker_registry.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-docker-registry-nginx
    namespace: infrabox-system
    labels:
        app: infrabox
        infrabox.net/component: docker-registry-nginx
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: infrabox
                infrabox.net/component: docker-registry-nginx
        spec:
            {{- if .Values.docker_registry.node_selector }}
            nodeSelector:
{{ toYaml .Values.docker_registry.node_selector | indent 16 }}
            {{- end }}
            containers:
            -
                name: nginx
                image: {{ .Values.general.docker_registry }}/{{ default "infrabox/docker-registry/nginx" .Values.docker_registry.nginx_image }}:{{ .Values.docker_registry.nginx_tag }}
                imagePullPolicy: Always
                env:
                -
                    name: INFRABOX_DOCKER_REGISTRY_ADMIN_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: infrabox-docker-registry
                            key: password
                -
                    name: INFRABOX_DOCKER_REGISTRY_ADMIN_USERNAME
                    valueFrom:
                        secretKeyRef:
                            name: infrabox-docker-registry
                            key: username
                livenessProbe:
                    httpGet:
                        path: /ping
                        port: 8080
                    initialDelaySeconds: 5
                    periodSeconds: 30
                readinessProbe:
                    httpGet:
                        path: /ping
                        port: 8080
                    initialDelaySeconds: 3
                    periodSeconds: 3
{{ end }}
