{{ if .Values.docker_registry.enabled }}
kind: Service
apiVersion: v1
metadata:
    name: infrabox-docker-registry
    namespace: infrabox-system
    labels:
        app: infrabox
        infrabox.net/component: docker-registry
spec:
    selector:
        app: infrabox
        infrabox.net/component: docker-registry
    ports:
    -
        protocol: TCP
        port: 8080
        targetPort: 5000
{{ end }}
