{{ define "ing_dashboard" }}
-
    pathType: Prefix
    path: /dashboard
    backend:
        service:
            name: infrabox-static
            port: 
                number: 80
{{ end }}

{{ define "ing_root" }}
-
    pathType: Prefix
    path: /
    backend:
        service:
            name: infrabox-static
            port: 
                number: 80
{{ end }}

{{ define "ing_github"}}
-
    pathType: Prefix
    path: /github/hook
    backend:
        service:
            name: infrabox-github-trigger
            port: 
                number: 8080
-
    pathType: Prefix
    path: /github/auth
    backend:
        service:
            name: infrabox-api
            port: 
                number: 8080
{{ end }}

{{ define "ing_saml"}}
-
    pathType: Prefix
    path: /saml
    backend:
        service:
            name: infrabox-api
            port: 
                number: 8080
{{ end }}


{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: infrabox
    namespace: {{ template "system_namespace" . }}
    annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "2048m"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "1200"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        nginx.ingress.kubernetes.io/affinity: "cookie"
        nginx.ingress.kubernetes.io/session-cookie-name: "route"
        nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        {{ if .Values.ingress.use_kube_lego }}
        kubernetes.io/tls-acme: "true"
        {{ end }}
spec:
    ingressClassName: nginx
    rules:
    -
        host: {{ .Values.host }}
        http:
            paths:
            {{ if .Values.ha.enabled }}
                {{ include "ing_dashboard" . | indent 12 }}
            {{ else if eq .Values.cluster.name "master" }}
                {{ include "ing_dashboard" . | indent 12 }}
            {{ end }}
            -
                pathType: Prefix
                path: /api
                backend:
                    service:
                        name: infrabox-api
                        port: 
                            number: 8080
            {{ if .Values.github.enabled }}
            {{ if .Values.ha.enabled }}
                {{ include "ing_github" . | indent 12 }}
            {{ else if eq .Values.cluster.name "master" }}
                {{ include "ing_github" . | indent 12 }}
            {{ end }}
            {{ end }}
            {{ if .Values.account.saml.enabled }}
            {{ if .Values.ha.enabled }}
                {{ include "ing_saml" . | indent 12 }}
            {{ else if eq .Values.cluster.name "master" }}
                {{ include "ing_saml" . | indent 12 }}
            {{ end }}
            {{ end }}
            -
                pathType: Prefix
                path: /v2
                backend:
                    service:
                        name: infrabox-docker-registry
                        port: 
                            number: 8080
            {{ if .Values.monitoring.enabled }}
            -
                pathType: Prefix
                path: /grafana
                backend:
                    service:
                        name: infrabox-grafana
                        port: 
                            number: 80
            {{ end }}
            {{ if eq .Values.cluster.name "master" }}
            -
                pathType: Prefix
                path: /
                backend:
                    service:
                        name: infrabox-static
                        port: 
                            number: 80
            {{ end }}
            {{ if .Values.ha.enabled }}
                {{ include "ing_root" . | indent 12 }}
            {{ else if eq .Values.cluster.name "master" }}
                {{ include "ing_root" . | indent 12 }}
            {{ end }}
    tls:
        - hosts:
            - {{ .Values.host }}
          secretName: {{ .Values.tls.cert_secret }}
{{ end }}
