{{ if .Values.docker_registry.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-docker-registry-nginx
    namespace: infrabox-system
    labels:
        app: infrabox
        infrabox.net/component: docker-registry-nginx
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: infrabox
                infrabox.net/component: docker-registry-nginx
        spec:
            {{- if .Values.docker_registry.node_selector }}
            nodeSelector:
{{ toYaml .Values.docker_registry.node_selector | indent 16 }}
            {{- end }}
            containers:
            -
                name: nginx
                image: {{ .Values.general.docker_registry }}/{{ default "infrabox/docker-registry/nginx" .Values.docker_registry.nginx_image }}:{{ .Values.docker_registry.nginx_tag }}
                imagePullPolicy: Always
                env:
                -
                    name: INFRABOX_DOCKER_REGISTRY_ADMIN_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: infrabox-docker-registry
                            key: password
                -
                    name: INFRABOX_DOCKER_REGISTRY_ADMIN_USERNAME
                    valueFrom:
                        secretKeyRef:
                            name: infrabox-docker-registry
                            key: username
                -
                    name: INFRABOX_DOCKER_REGISTRY_TLS_ENABLED
                    value: {{ default "false" .Values.docker_registry.tls.enabled | quote }}
                volumeMounts:
                {{ if .Values.docker_registry.tls.enabled }}
                -
                    name: registry-tls
                    mountPath: /var/run/infrabox
                    readOnly: true
                {{ end }}
            volumes:
            {{ if .Values.docker_registry.tls.enabled }}
            -
                name: registry-tls
                secret:
                    secretName: infrabox-docker-registry-tls
            {{ end }}
{{ end }}
