apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-postgres
    namespace: infrabox-system
    labels:
        app: infrabox
        infrabox.net/component: postgres
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: infrabox
                infrabox.net/component: postgres
        spec:
            nodeSelector:
                cloud.google.com/gke-nodepool: default-pool
            containers:
            -
                image: us.gcr.io/test-kubernetes-167921/infrabox/postgres:build_INFRABOX_BUILD_NUMBER
                name: postgres
---
kind: Service
apiVersion: v1
metadata:
    name: infrabox-postgres
    namespace: infrabox-system
    labels:
        app: infrabox
        infrabox.net/component: postgres
spec:
    selector:
        app: infrabox
        infrabox.net/component: postgres
    ports:
    -
        protocol: TCP
        port: 5432
        targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
    name: infrabox-postgres
    namespace: infrabox-system
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
    name: infrabox-postgres
    namespace: infrabox-worker
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
