{{ if .Values.general.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infrabox-leader-elector
  namespace: infrabox-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: infrabox-system
  name: infrabox-leader-elector
rules:
- apiGroups: [""]
  resources:
  - endpoints
  verbs:
  - get
  - post
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: infrabox-leader-elector
  namespace: infrabox-system
subjects:
- kind: ServiceAccount
  name: infrabox-leader-elector
  namespace: infrabox-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{ end }}
