apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ibfunctions.core.infrabox.net
spec:
  group: core.infrabox.net
  names:
    kind: IBFunction
    listKind: IBFunctionList
    plural: ibfunctions
    singular: ibfunction
  scope: Cluster
  versions: 
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            json:
              x-kubernetes-preserve-unknown-fields: true
