apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ibpipelineinvocations.core.infrabox.net
spec:
  group: core.infrabox.net
  names:
    kind: IBPipelineInvocation
    listKind: IBPipelineInvocationList
    plural: ibpipelineinvocations
    singular: ibpiplineinvocation
  scope: Namespaced
  versions: 
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              x-kubernetes-preserve-unknown-fields: true
            status:
              x-kubernetes-preserve-unknown-fields: true
