apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-postgres
    namespace: infrabox-system
    labels:
        app: infrabox
        infrabox.net/component: postgres
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: infrabox
                infrabox.net/component: postgres
        spec:
            containers:
            -
                image: {{ .Values.docker_registry }}/{{ .Values.image }}:{{ .Values.tag }}
                name: postgres
---
kind: Service
apiVersion: v1
metadata:
    name: infrabox-postgres
    namespace: infrabox-system
    labels:
        app: infrabox
        infrabox.net/component: postgres
spec:
    selector:
        app: infrabox
        infrabox.net/component: postgres
    ports:
    -
        protocol: TCP
        port: 5432
        targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
    name: infrabox-postgres-db-credentials
    namespace: infrabox-system
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
    name: infrabox-postgres-db-credentials
    namespace: infrabox-worker
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
