apiVersion: v1
kind: ConfigMap
metadata:
  name: infrabox-fluent-bit
  namespace: {{ template "system_namespace" . }}
data:
  parsers.conf: |-
    # CRI Parser
    [PARSER]
        # http://rubular.com/r/tjUt3Awgg4
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
  fluent-bit.conf: |-
    [SERVICE]
        Flush        2
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
    [INPUT]
        Name             tail
        Path             /var/log/containers/*{{- template "worker_namespace" . -}}*.log
        Parser           cri
        Tag              kube.*
        Refresh_Interval 2
        Mem_Buf_Limit    200MB
        Skip_Long_Lines  On
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    [OUTPUT]
        Name  http
        Match *
        Host infrabox-api.{{ template "system_namespace" . }}
        Port 8080
        URI /internal/api/job/consoleupdate
        Format json
