{{ define "db_job" }}
apiVersion: batch/v1
kind: Job
metadata:
    name: infrabox-db-migration
    namespace: {{ template "system_namespace" . }}
    # {{ if .Values.database.cloudsql.enabled }}
    # # The cloudsql proxy does not stop and helm would time out
    # {{ else }}
    # annotations:
    #     "helm.sh/hook": "pre-install,pre-upgrade" # use the pre-install hook, otherwise the e2e test installation may hang
    #     "helm.sh/hook-delete-policy": "before-hook-creation"
    # {{ end }}
    # post-install hook may cause the e2e test installation hang, 
    # because scheduler is crashing since there is no database table
    # But pre-install hook doesn't work either, since this job needs objects like rsa secrets
    annotations:
        # since job template is immutable, we need to delete it first before sync
        argocd.argoproj.io/hook: Sync
        argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
        # FIXME: set some annotations for helm
spec:
    template:
        metadata:
            name: infrabox-db-migration
        spec:
            {{ include "imagePullSecret" . | indent 8 }}
            containers:
            {{ include "containers_database" . | indent 12 }}
            -
                name: migrate
                image: {{ include "image_repository" . }}/db:{{ include "image_tag" . }}
                env:
                {{ include "env_database" . | indent 16 }}
                {{ include "env_general" . | indent 16 }}
                -
                    name: INFRABOX_ADMIN_EMAIL
                    valueFrom:
                        secretKeyRef:
                            name: infrabox-admin
                            key: email
                -
                    name: INFRABOX_ADMIN_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: infrabox-admin
                            key: password
                volumeMounts:
                {{ include "mounts_rsa_public" . | indent 16 }}
                {{ include "mounts_rsa_private" . | indent 16 }}
            restartPolicy: OnFailure
            volumes:
                {{ include "volumes_database" . | indent 16 }}
                {{ include "volumes_rsa" . | indent 16 }}
{{ end }}

{{ if .Values.ha.enabled }}
    {{ include "db_job" . }}
{{ else if eq .Values.cluster.name "master" }}
    {{ include "db_job" . }}
{{ end }}
