apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ibfunctions.core.infrabox.net
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: core.infrabox.net
  names:
    kind: IBFunction
    listKind: IBFunctionList
    plural: ibfunctions
    singular: ibfunction
  scope: Cluster
  versions: 
    - name: v1alpha1
      served: true
      storage: true
