{{ if .Values.gerrit.enabled }}
{{ if .Values.general.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infrabox-gerrit-sa
  namespace: infrabox-system
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: infrabox-system
  name: infrabox-gerrit-role
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: infrabox-gerrit-rb
  namespace: infrabox-system
subjects:
- kind: ServiceAccount
  name: infrabox-gerrit-sa
  namespace: infrabox-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
{{ end }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-gerrit
    namespace: infrabox-system
    labels:
        app: infrabox
        infrabox.net/component: gerrit
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: infrabox
                infrabox.net/component: gerrit
        spec:
            {{- if .Values.general.rbac.enabled }}
            serviceAccountName: infrabox-gerrit-sa
            {{ end }}
            {{- if .Values.gerrit.node_selector }}
            nodeSelector:
{{ toYaml .Values.gerrit.node_selector | indent 16 }}
            {{- end }}
            containers:
            {{ if .Values.storage.cloudsql.enabled }}
            -
                image: gcr.io/cloudsql-docker/gce-proxy:1.09
                name: cloudsql-proxy
                command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                          "-instances={{ .Values.storage.cloudsql.instance_connection_name }}=tcp:5432",
                          "-credential_file=/secrets/cloudsql/credentials.json"]
                volumeMounts:
                - name: cloudsql-instance-credentials
                  mountPath: /secrets/cloudsql
                  readOnly: true
                - name: ssl-certs
                  mountPath: /etc/ssl/certs
                - name: cloudsql
                  mountPath: /cloudsql
            {{ end }}
            -
                name: gerrit-trigger
                image: {{ required "general.docker_registry is required" .Values.general.docker_registry }}/{{ default "infrabox/gerrit/trigger" .Values.gerrit.trigger.image }}:{{ required "gerrit.trigger.tag is required" .Values.gerrit.trigger.tag }}
                imagePullPolicy: Always
                env:
                {{ include "env_database" . | indent 16 }}
                {{ include "env_gerrit" . | indent 16 }}
                {{ include "env_general" . | indent 16 }}
                -
                    name: INFRABOX_SERVICE
                    value: {{ default "infrabox/gerrit/trigger" .Values.gerrit.trigger.image }}
                -
                    name: INFRABOX_VERSION
                    value: {{ required "gerrit.trigger.tag is required" .Values.gerrit.trigger.tag }}
                volumeMounts:
                - name: gerrit-ssh
                  mountPath: /tmp/gerrit
                  readOnly: true
            {{ if .Values.gerrit.review.enabled }}
            -
                name: gerrit-review
                image: {{ required "general.docker_registry is required" .Values.general.docker_registry }}/{{ default "infrabox/gerrit/review" .Values.gerrit.review.image }}:{{ required "gerrit.review.tag is required" .Values.gerrit.review.tag }}
                imagePullPolicy: Always
                env:
                {{ include "env_database" . | indent 16 }}
                {{ include "env_gerrit" . | indent 16 }}
                {{ include "env_general" . | indent 16 }}
                -
                    name: INFRABOX_SERVICE
                    value: {{ default "infrabox/gerrit/review" .Values.gerrit.review.image }}
                -
                    name: INFRABOX_VERSION
                    value: {{ required "gerrit.tag is required" .Values.gerrit.review.tag }}
                -
                    name: INFRABOX_DASHBOARD_URL
                    value: {{ .Values.dashboard.url }}
                volumeMounts:
                - name: gerrit-ssh
                  mountPath: /tmp/gerrit
                  readOnly: true
            {{ end }}
            -
                name: leader-elector
                image: "gcr.io/google_containers/leader-elector:0.5"
                args:
                    - "--election"
                    - infrabox-gerrit
                    - "--http=0.0.0.0:4040"
                ports:
                - containerPort: 4040
            volumes:
              - name: gerrit-ssh
                secret:
                  secretName: infrabox-gerrit-ssh
            {{- if .Values.storage.cloudsql.enabled }}
              - name: cloudsql-instance-credentials
                secret:
                  secretName: infrabox-cloudsql-instance-credentials
              - name: ssl-certs
                hostPath:
                  path: /etc/ssl/certs
              - name: cloudsql
                emptyDir:
            {{- end }}
{{ end }}
